### ISSUE TITLE
firamath-otf package not available on Fedora

### ISSUE THREAD

**Issue by bertvv** [pvdk/hogent-latex-thesis#1]
On Fedora, the package `firamath-otf` is not part of the texlive distribution. Consequently, the example file will fail to compile. As a workaround, [line 171 of hogentthesis.cls](https://github.com/pvdk/hogent-latex-thesis/blob/master/hogentthesis.cls#L171):

```latex
\RequirePackage{firamath-otf}
```

can be commented out without any noticeable effect on the result.

**Comment by pvdk** [comment]
Hey @bertvv,

You're absolutely right. I looked into it and firamath-otf is pretty useless: it is rather new and it only provides a "convenient" way to access the system fonts, the package itself does _not_ ship the fonts.
Also, because firamath itself is rather new, it is trying to keep up with a moving target: the author of fira math recently added bold support, but that hasn't made it into firamath_otf yet.

So since we're already shipping fallback fonts and the package is useless and unavailable, I decided to remove it in the _mathfix_ branch. Closing this issue, please feel free to reply on this in the other issue.
