### ISSUE TITLE
Math text is too bold

### ISSUE THREAD

**Issue by bertvv** [pvdk/hogent-latex-thesis#2]
The math font is slightly bolder than normal text. This draws unnecessary attention to equations and math mode text within a paragraph. I would suggest to drop the FakeBold option when setting the math font ([hogentthesis.cls:362](https://github.com/pvdk/hogent-latex-thesis/blob/master/hogentthesis.cls#L362)):

```latex
\setmathfont{Fira Math Regular}[FakeSlant]
```

**Comment by pvdk** [comment]
Hey @bertvv, thanks for the report.

I pushed a fix to the _mathfix_ branch, please check it out: https://github.com/pvdk/hogent-latex-thesis/commit/a4eab8dd7e05ee1b61c2cba791505071dc47b973
(Turns out TeXstudio does line endings on a per-file basis, hogentthesis.cls was still using carriage returns, that's why that commit is adds 599 lines :smile: )

When looking into the problem I also noticed the fallback font wasn't working, that should be fixed too.
This should also take care of #1.

**Comment by bertvv** [comment]
Looks great now! Merge to master, as far as I'm concerned. ;-)
